name: CI -Build Docker Image

on: 
  push: 
    branches: [master]

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t expense-tracker . 
      
      - name: Smoke test - container starts 
        run : | 
          docker run -d -p 5000:5000 --name test-app expense-tracker
          sleep 3
          curl --fail http://localhost:5000
          docker stop test-app